# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
