# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItunesMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('copyright', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('webmaster', models.CharField(max_length=255)),
            ],
        ),
    ]
