# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itunesmetadata',
            name='podcast',
        ),
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(default='Davinder Mahal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.CharField(default='SciFi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='email',
            field=models.EmailField(default='webmaster@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='image_url',
            field=models.CharField(default='hello.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='owner',
            field=models.CharField(default='Davinder', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='subtitle',
            field=models.CharField(default='Doctor Who subtitle', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='summary',
            field=models.CharField(default='A Doctor Who podcast', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItunesMetaData',
        ),
    ]
