# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.IntegerField(choices=[(1, 'Audio'), (2, 'Video')], default=1),
        ),
    ]
