# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20160827_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Episode')),
            ],
        ),
    ]
