# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20160830_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mime',
            field=models.IntegerField(choices=[(1, 'audio/mpeg'), (2, 'video/mp4')], default=1),
        ),
    ]
