# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_audio_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='mime',
            field=models.CharField(default='audio/mpeg', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='mime',
            field=models.CharField(default='video/mp4', max_length=40),
            preserve_default=False,
        ),
    ]
